export declare const config: {
    NODE_ENV: string;
    PORT: number;
    FRONTEND_URL: string;
    DATABASE_URL: string;
    DATABASE_PUBLIC_URL: string;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    SMTP_HOST: string;
    SMTP_PORT: number;
    SMTP_USER: string;
    SMTP_PASS: string;
    FROM_EMAIL: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    AWS_ACCESS_KEY_ID: string;
    AWS_SECRET_ACCESS_KEY: string;
    AWS_REGION: string;
    AWS_S3_BUCKET: string;
    RATE_LIMIT_WINDOW_MS: number;
    RATE_LIMIT_MAX_REQUESTS: number;
    LOG_LEVEL: string;
    LOG_FILE: boolean;
    ENABLE_MOCK_MODE: boolean;
    ENABLE_DATABASE: boolean;
    RAILWAY_ENVIRONMENT_NAME: string | undefined;
    RAILWAY_DEPLOYMENT_ID: string | undefined;
    VERCEL_URL: string | undefined;
    HEROKU_APP_NAME: string | undefined;
};
export declare const isProduction: boolean;
export declare const isDevelopment: boolean;
export declare const isTest: boolean;
export default config;
//# sourceMappingURL=environment.d.ts.map